using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Windows.Controls;

namespace GameOfLife {
    static class Program {
        

        /// <summary>
        /// Der Haupteinstiegspunkt für die Anwendung.
        /// </summary>
        [STAThread]
        static void Main() {
            
            ///Generated by Visual Studio
            ///Enables Visual Styles on the Form
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            ///Runs the Form
            Application.Run(new Form1());


        }
    }
}
